// src/config/feeds.js
// Liste complète de tous les flux RSS Metal & Rock (news, labels, webzines)

const RSS_FEEDS = [
  // ─── METAL — WEBZINES ────────────────────────────────────────────────────
  {
    name: 'Blabbermouth',
    url: 'https://www.blabbermouth.net/feed/',
    category: 'metal',
    icon: '🤘',
    color: 0xe74c3c,
  },
  {
    name: 'Metal Injection',
    url: 'https://metalinjection.net/feed',
    category: 'metal',
    icon: '💉',
    color: 0xe74c3c,
  },
  {
    name: 'MetalSucks',
    url: 'https://www.metalsucks.net/feed/',
    category: 'metal',
    icon: '🎸',
    color: 0xe74c3c,
  },
  {
    name: 'Angry Metal Guy',
    url: 'https://www.angrymetalguy.com/feed/',
    category: 'metal',
    icon: '😡',
    color: 0xe74c3c,
    allowReviews: true,
  },
  {
    name: 'No Clean Singing',
    url: 'https://www.nocleansinging.com/feed/',
    category: 'metal',
    icon: '🔇',
    color: 0xe74c3c,
    disabled: true,
  },
  {
    name: 'Invisible Oranges',
    url: 'https://www.invisibleoranges.com/feed/',
    category: 'metal',
    icon: '🟠',
    color: 0xe74c3c,
  },
  {
    name: 'Decibel Magazine',
    url: 'https://www.decibelmagazine.com/feed/',
    category: 'metal',
    icon: '🔊',
    color: 0xe74c3c,
  },
  {
    name: 'Metal Addicts',
    url: 'https://www.metaladdicts.com/feed/',
    category: 'metal',
    icon: '⚗️',
    color: 0xe74c3c,
  },
  {
    name: 'Bravewords',
    url: 'https://bravewords.com/feed/',
    category: 'metal',
    icon: '⚔️',
    color: 0xe74c3c,
  },
  {
    name: 'The Obelisk',
    url: 'https://theobelisk.net/obelisk/feed/',
    category: 'metal',
    icon: '🗿',
    color: 0xe74c3c,
    allowReviews: true,
  },
  {
    name: 'Lambgoat',
    url: 'https://www.lambgoat.com/feed/',
    category: 'metal',
    icon: '🐐',
    color: 0xe74c3c,
    disabled: true,
  },
  {
    name: 'Metal-Rules',
    url: 'https://www.metal-rules.com/feed/',
    category: 'metal',
    icon: '📏',
    color: 0xe74c3c,
  },
  {
    name: 'Bandcamp Daily',
    url: 'https://daily.bandcamp.com/feed',
    category: 'metal',
    icon: '🎵',
    color: 0xe74c3c,
  },
  {
    name: 'Metal Underground',
    url: 'https://www.metalunderground.com/news/rss.cfm',
    category: 'metal',
    icon: '⛏️',
    color: 0xe74c3c,
    disabled: true,
  },
  {
    name: 'Metal Hammer',
    url: 'https://www.loudersound.com/metal-hammer/feed',
    category: 'metal',
    icon: '🔨',
    color: 0xe74c3c,
  },
  {
    name: 'Terrorizer',
    url: 'https://terrorizer.com/feed/',
    category: 'metal',
    disabled: true,
    icon: '☠️',
    color: 0xe74c3c,
  },

  // ─── ROCK — WEBZINES ─────────────────────────────────────────────────────
  {
    name: 'Loudwire',
    url: 'https://loudwire.com/feed/',
    category: 'rock',
    icon: '📣',
    color: 0xe67e22,
  },
  {
    name: 'NME',
    url: 'https://www.nme.com/feed',
    category: 'rock',
    icon: '🎤',
    color: 0xe67e22,
    strict: true,
  },
  {
    name: 'Consequence of Sound',
    url: 'https://consequenceofsound.net/feed',
    category: 'rock',
    icon: '🎼',
    color: 0xe67e22,
    strict: true,
  },
  {
    name: 'Alternative Press',
    url: 'https://www.altpress.com/feed/',
    category: 'rock',
    icon: '🎸',
    color: 0xe67e22,
    strict: true,
  },
  {
    name: 'Louder Sound',
    url: 'https://www.loudersound.com/feeds/all',
    category: 'rock',
    icon: '🔉',
    color: 0xe67e22,
  },
  {
    name: 'Rock Sound',
    url: 'https://www.rocksound.tv/feed',
    category: 'rock',
    icon: '🎚️',
    color: 0xe67e22,
  },
  {
    name: 'Revolver Magazine',
    url: 'https://www.revolvermag.com/rss.xml',
    category: 'rock',
    icon: '🔫',
    color: 0xe67e22,
  },
  {
    name: 'Spin',
    url: 'https://www.spin.com/feed/',
    category: 'rock',
    icon: '💿',
    color: 0xe67e22,
    strict: true,
  },
  {
    name: 'The Pit',
    url: 'https://thepitmagazine.com/feed/',
    category: 'rock',
    icon: '🎪',
    color: 0xe67e22,
  },
  {
    name: 'Stereogum',
    url: 'https://www.stereogum.com/feed/',
    category: 'rock',
    icon: '🎧',
    color: 0xe67e22,
    strict: true,
  },
  {
    name: 'Kerrang!',
    url: 'https://www.kerrang.com/rss',
    category: 'rock',
    icon: '💥',
    color: 0xe67e22,
    disabled: true,
  },
  {
    name: 'Upset Magazine',
    url: 'https://www.upsetmagazine.com/feed/',
    category: 'rock',
    disabled: true,
    icon: '📰',
    color: 0xe67e22,
  },
  {
    name: 'Sputnikmusic',
    url: 'https://www.sputnikmusic.com/rss/albums.php',
    category: 'rock',
    icon: '🛸',
    color: 0xe67e22,
    disabled: true,
  },
  {
    name: 'The PRP',
    url: 'https://theprp.com/feed/',
    category: 'metal',
    icon: '🎧',
    color: 0xe74c3c,
  },

  // ─── LABELS ──────────────────────────────────────────────────────────────
  {
    name: 'Season of Mist',
    url: 'https://www.season-of-mist.com/news/feed/',
    category: 'label',
    icon: '🌫️',
    color: 0x9b59b6,
  },
  {
    name: 'Peaceville Records',
    url: 'https://www.peaceville.com/feed/',
    category: 'label',
    icon: '☮️',
    color: 0x9b59b6,
  },
  {
    name: 'Dark Descent Records',
    url: 'https://www.darkdescentrecords.com/feed/',
    category: 'label',
    icon: '🌑',
    color: 0x9b59b6,
  },
  {
    name: 'Nuclear Blast',
    url: 'https://www.nuclearblast.de/rss/news/',
    category: 'label',
    icon: '☢️',
    color: 0x9b59b6,
    disabled: true,
  },
  {
    name: 'Century Media',
    url: 'https://www.centurymedia.com/feed/',
    category: 'label',
    disabled: true,
    icon: '🎵',
    color: 0x9b59b6,
  },
  {
    name: 'Napalm Records',
    url: 'https://www.napalmrecords.com/feed/',
    category: 'label',
    icon: '🔥',
    color: 0x9b59b6,
    disabled: true,
  },
  {
    name: 'Relapse Records',
    url: 'https://www.relapse.com/feed/',
    category: 'label',
    disabled: true,
    icon: '🕺',
    color: 0x9b59b6,
  },
  {
    name: 'Metal Blade Records',
    url: 'https://www.metalblade.com/feed/',
    category: 'label',
    icon: '🗡️',
    color: 0x9b59b6,
    disabled: true,
  },
  {
    name: 'Prosthetic Records',
    url: 'https://prostheticrecords.com/feed/',
    category: 'label',
    icon: '🦴',
    color: 0x9b59b6,
  },
];

// Tags Spotify pour les genres metal/rock
const SPOTIFY_GENRE_SEEDS = [
  'metal',
  'heavy-metal',
  'black-metal',
  'death-metal',
  'thrash-metal',
  'doom-metal',
  'power-metal',
  'progressive-metal',
  'metalcore',
  'rock',
  'hard-rock',
  'classic-rock',
  'alternative-rock',
  'punk',
  'grunge',
  'indie-rock',
];

// Tags Last.fm à surveiller
const LASTFM_TAGS = [
  'metal',
  'heavy metal',
  'black metal',
  'death metal',
  'thrash metal',
  'doom metal',
  'power metal',
  'metalcore',
  'rock',
  'hard rock',
  'classic rock',
];

module.exports = { RSS_FEEDS, SPOTIFY_GENRE_SEEDS, LASTFM_TAGS };
